package com.piecehk.werewolf.core.event;

public enum EventType {
    GAME_STARTED,
    ROLE_ASSIGNED,
    PHASE_CHANGED,
    WOLF_DISCUSSION,
    WOLF_KILL_DECIDED,
    SEER_CHECKED,
    WITCH_ACTED,
    PLAYER_DIED,
    PLAYER_SPOKE,
    SHERIFF_ELECTION_STARTED,
    SHERIFF_RUN_DECLARED,
    SHERIFF_WITHDREW,
    SHERIFF_VOTE_CAST,
    SHERIFF_ELECTED,
    SPEECH_ORDER_CHOSEN,
    BADGE_TRANSFERRED,
    VOTE_CAST,
    PLAYER_EXILED,
    HUNTER_SHOT,
    GAME_OVER,
    SYSTEM_NOTE
}
